### ISSUE TITLE
If no args givein in pizza builder, then show help

### ISSUE THREAD

**Issue by Rob-McCormack** [JacobCallahan/Understanding#1]
I added this to cause help to show if no arguments 
```python
@click.command(no_args_is_help=True)
```  

which I think would be the preferred behavior.

ref: https://github.com/JacobCallahan/Understanding/blob/master/Python/click_cli/pizza_builder.py)

Thanks for great tutorial!

**Comment by JacobCallahan** [comment]
Great suggestion. Since these files are point-in-time from when they were recorded, I won't be updating them after upload. However, If I touch on click again, I will try to remember to include this tip!
